apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:                           # this is equivalent to the 'data' field in a Pod definition
  cource: "DevSecOps with aws"
  duration: "120hrs"
  trainer: "Kishore"