apiVersion: v1
kind: Pod
metadata:
  name: config-map-demo
spec:
  containders:
  - name: nginx
    image: nginx
    envFrom:                # this section is used to reference from the ConfigMap
    - configMapRef:
        name: pod-config